name: Database migration

on:
  release:
    types: [ published ]

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Migrate Pre-Production database
        run: |
          ./mvnw -B -f entities/pom.xml flyway:migrate \
#          -Ddatabase.url=${{preprod.database.url}} \
#          -Ddatabase.user=${{preprod.database.user}} \
#          -Ddatabase.password=${{preprod.database.password}}
      - name: Migrate Production database
        run: |
          ./mvnw -B -f entities/pom.xml flyway:migrate \
#          -Ddatabase.url=${{prod.database.url}} \
#          -Ddatabase.user=${{prod.database.user}} \
#          -Ddatabase.password=${{prod.database.password}}
