name: Deploy Data Domain artifacts & Clean repository

on:
  release:
    types: [ published ]

jobs:
  deploy-artifacts:
    runs-on: ubuntu-latest
    needs: build-application
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Deploy to GitHub Packages
        run: ./mvnw -B deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  clean-repository:
    runs-on: ubuntu-latest
    needs: deploy-application
    steps:
      - name: Delete older versions of Borealis Data Domain Parent
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.domain-parent'
          min-versions-to-keep: 2
      - name: Delete older versions of Borealis Data Entities
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.entities'
          min-versions-to-keep: 2
      - name: Delete older versions of Borealis Data Repositories
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.repositories'
          min-versions-to-keep: 2
