# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Deploy Data Domain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  migrate-database:
    if: {{false}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Migrate database
          run: |
            ./mvnw -B flyway:migrate \
            -Ddatabase.url=${{database.url}} \
            -Ddatabase.user=${{database.user}} \
            -Ddatabase.password=${{database.password}} \
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          ./mvnw -B clean install \
#          -Ddatabase.url=${{database.url}} \
#          -Ddatabase.user=${{database.user}} \
#          -Ddatabase.password=${{database.password}} \
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Quality analysis
        run: |
          ./mvnw -B sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=borealis \
          -Dsonar.projectKey=${{github.event.repository.name}} \
          -Dsonar.branch=${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONARCLOUD_LOGIN}}
  deploy-application:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy to GitHub Packages
        run: ./mvnw -B deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  clean-repository:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Delete older versions of Borealis Data Domain Parent
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.domain-parent'
          min-versions-to-keep: 2
      - name: Delete older versions of Borealis Data Entities
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.entities'
          min-versions-to-keep: 2
      - name: Delete older versions of Borealis Data Repositories
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.data.repositories'
          min-versions-to-keep: 2
