name: Deploy Data Domain artifacts & Clean repository

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy-artifacts:
    name: Deploy Maven artifacts to GitHub Packages
    runs-on: ubuntu-latest
    needs: [ build-application ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Deploy to GitHub Packages
        run: ./mvnw -B deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  clean-repository:
    name: Remove old versions from GitHub Packages
    runs-on: ubuntu-latest
    needs: deploy-application
    steps:
      - name: Delete older versions of Borealis Daycare Center Domain Parent
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.parent'
          min-versions-to-keep: 2

      - name: Delete older versions of Borealis Daycare Center Entities
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.entities'
          min-versions-to-keep: 2

      - name: Delete older versions of Borealis Daycare Center Repositories
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.repositories'
          min-versions-to-keep: 2
